[[plugins]]
repo = 'w0rp/ale'
on_ft = ['python']

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
on_ft = ['python']
hook_source = '''
    let g:deoplete#enable_at_startup = 1
    inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
'''

[[plugins]]
repo = "davidhalter/jedi-vim"
on_ft = ['python']
